plugins {
    id 'com.android.application'
}

android {
    namespace 'id.bram.flipclock'
    compileSdk 34

    defaultConfig {
        applicationId 'id.bram.flipclock'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    signingConfigs {
        fixed {
            storeFile file('flipclock.keystore')
            storePassword 'flipclock123'
            keyAlias 'flipclock'
            keyPassword 'flipclock123'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.fixed
        }
        debug {
            signingConfig signingConfigs.fixed
        }
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.11.0'
}
